In [3]:
list3=["apple","mango","cherry"]
list3

['apple', 'mango', 'cherry']

In [1]:
list4=["Phanz",3,4,5.66]
list4

['Phanz', 3, 4, 5.66]

In [4]:
list5=list3+list4
list5

['apple', 'mango', 'cherry', 'Phanz', 3, 4, 5.66]

In [ ]:
list3[2]

'cherry'

In [ ]:
list3[2:]

['cherry']

In [ ]:
list4[1::1]

[3, 4, 5.66]

In [ ]:
list3[-1:1]

[]

In [5]:
list3[1]="mango"
list3

['apple', 'mango', 'cherry']

In [7]:
for x in list3:
  x
  print("x")

x
x
x


In [6]:
if "apple" in list3:
  print("yes")

yes


In [ ]:
if"app"in list3:
  print("yes")

In [ ]:
len(list4)

4

In [ ]:
list3.append("hey")

In [8]:
list3

['apple', 'mango', 'cherry']

In [ ]:
list4.insert(2,"mylist")
list4

['teju', 3, 'mylist', 4, 5.66]

In [ ]:
list3.remove("hey")
list3

['apple', 'stuffi', 'cherry', 'hey']

In [ ]:
list3.pop()
list3

['apple', 'stuffi', 'cherry']

In [ ]:
list3.clear()
list3

[]

In [ ]:
del list4

In [ ]:
list6=["all","the","best"]
list7=["monu","tonu","jinu"]
list6
list7

['monu', 'tonu', 'jinu']

In [ ]:
list6

['all', 'the', 'best']

In [ ]:
mylist=list6.copy()
mylist

['all', 'the', 'best']

In [ ]:
for x in list6:
  list7.append(x)
  list7

In [ ]:
list6.extend(list7)
list6

['all',
 'the',
 'best',
 'monu',
 'tonu',
 'jinu',
 'all',
 'the',
 'best',
 'all',
 'the',
 'best']

In [ ]:
list6.count(1)

0

In [ ]:
list6.count("all")

3

In [ ]:
list7.reverse()
list7

['monu', 'tonu', 'jinu', 'all', 'the', 'best', 'all', 'the', 'best']

In [ ]:
list7.sort()
list7

['all', 'all', 'best', 'best', 'jinu', 'monu', 'the', 'the', 'tonu']

In [ ]:
list7.remove("all")
list7

['all', 'best', 'best', 'jinu', 'monu', 'the', 'the', 'tonu']

In [ ]:
list8=[1,2,3,4,5,6]
list8

[1, 2, 3, 4, 5, 6]

In [ ]:
a = [1,2,3,"raju","kiku","jasmine"]
print(a)

[1, 2, 3, 'raju', 'kiku', 'jasmine']


In [ ]:
b = set(a)

In [ ]:
b

{1, 2, 3, 'jasmine', 'kiku', 'raju'}

In [ ]:
b.pop()

'jasmine'

In [ ]:
b.pop()

1

In [ ]:
a.pop()

'jasmine'

In [ ]:
a.pop(4)

'kiku'

In [ ]:
a.clear()

In [ ]:
print(a)

[]


In [ ]:
del b

In [ ]:
print(b)

NameError: ignored

In [ ]:
c = ["apple","cherry","hen","hat","fat","hat"]

In [ ]:
print(c)

['apple', 'cherry', 'hen', 'hat', 'fat', 'hat']


In [ ]:
c.count("hat")

2

In [ ]:
c.count("orange")

0

In [ ]:
c.append("orange")

In [ ]:
c

['apple', 'cherry', 'hen', 'hat', 'fat', 'hat', 'orange']

In [ ]:
d = set(c)

In [ ]:
d

{'apple', 'cherry', 'fat', 'hat', 'hen', 'orange'}

In [ ]:
print(len(c))

7


In [ ]:
print(len(d))

6


In [ ]:
d.add("cat")

In [ ]:
d

{'apple', 'cat', 'cherry', 'fat', 'hat', 'hen', 'orange'}

In [ ]:
n=2
m=2
res=[[0 for i in range(m)]for j in range(n)]
print("the matrix"+str(res))

the matrix[[0, 0], [0, 0]]


In [ ]:
list9=[["banana","orange","apple"],[1,2,3]]
list9

[['banana', 'orange', 'apple'], [1, 2, 3]]

In [ ]:
list10=["tuffi","jenny","monkey"]
list10

['tuffi', 'jenny', 'monkey']

In [ ]:
list11=([3,4,5],
        [5,6,7])
list11

([3, 4, 5], [5, 6, 7])

In [ ]:
list12=[['a','b','c'],['d','e','f']]
list12

[['a', 'b', 'c'], ['d', 'e', 'f']]

In [ ]:
print(list12[1][2])

f


In [ ]:
print(list12[1][0])

d


In [ ]:
for x in list12:
  print(x)

['a', 'b', 'c']
['d', 'e', 'f']


In [1]:
import numpy as np

In [2]:
a = np.array([1,2])
print("a=\n",a)

a=
 [1 2]


In [3]:
b = np.array([[0,1],[2,2]])
b


array([[0, 1],
       [2, 2]])

In [4]:
print("a=\n",a,"b=\n",b)

a=
 [1 2] b=
 [[0 1]
 [2 2]]


In [5]:
c=a+b

In [6]:
print(c)

[[1 3]
 [3 4]]


In [7]:
np.sum(a)

3

In [8]:
r = np.arange(1,10)

In [9]:
r

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
p = np.array([[[1,2],[6,5],[5,4]]])

In [11]:
print(p)

[[[1 2]
  [6 5]
  [5 4]]]


In [12]:
np.sum(p)

23

In [13]:
np.linspace(2,10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [14]:
np.linspace(1,20,5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [15]:
print(p.dtype)

int64


In [16]:
#show 10 random element between 0-100
arr = np.random.randint(0,100,10)
arr

array([88,  2, 74, 90, 84, 79, 36, 45,  8, 33])

In [17]:
#check min element of list
arr.min()

2

In [18]:
#check maximum element
arr.max()

90

In [19]:
#create set
s1 = {'true',"maggi",1,5}

In [20]:
s1

{1, 5, 'maggi', 'true'}

In [21]:
# remove specified element of the set
s1.remove('true')

In [23]:
s1

{1, 5, 'maggi'}

In [24]:
s2 = {10,50,40,'false',"okay"}

In [25]:
s2

{10, 40, 50, 'false', 'okay'}

In [26]:
s3 = s1.intersection(s2)

In [27]:
s3

set()

In [28]:
s1.update([10,40,"true"])

In [29]:
s1

{1, 10, 40, 5, 'maggi', 'true'}

In [30]:
s3 = s1.intersection(s2)

In [31]:
s3

{10, 40}

In [32]:
a = 10
b = 20
if b>a:
  print("b is greater than a")
else:
  print("a is greater than b")

b is greater than a


In [33]:
l1 = [1,5,10,7]
l1

[1, 5, 10, 7]

In [34]:
i = 0
while(i<len(l1)):
  l1[i] = l1[i]+100
  i=i+1

In [35]:
l1

[101, 105, 110, 107]

In [40]:
def odd_even(x):
  if x % 2 == 0:
    print(x,"is even")
  else: 
    print(x,"is odd")

In [41]:
odd_even(10)

10 is even


In [42]:
odd_even(11)

11 is odd


In [43]:
x = np.array([[1,2],[7,5]])
x

array([[1, 2],
       [7, 5]])

In [44]:
#sum of columns
x.sum(axis=0)

array([8, 7])

In [45]:
#sum of rows
x.sum(axis=1)

array([ 3, 12])

In [46]:
#intialize all element as zero in matrix
a = np.zeros((2,2))

In [50]:
print(a)

[[0. 0.]
 [0. 0.]]


In [47]:
#initialize all element one in matrix
y = np.ones((3,3))

In [51]:
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [48]:
np.any(a!=0)

False

In [49]:
np.all(a==a)

True

In [52]:
import pandas as pd

In [53]:
df = pd.DataFrame({'name' : ['amit','zeny','banku','dheeraj'],'age':[10,12,14,15],'address' :['bhopal','bhilai','nagpur','mumbai'],'kg':[20,15,25,30]})

In [54]:
df

name  age address  kg
0     amit   10  bhopal  20
1     zeny   12  bhilai  15
2    banku   14  nagpur  25
3  dheeraj   15  mumbai  30

In [55]:
df = pd.DataFrame(data=np.random.randint(0,10),index = list("abcd"),columns= list("ABCD"))

In [56]:
df

A  B  C  D
a  9  9  9  9
b  9  9  9  9
c  9  9  9  9
d  9  9  9  9

In [57]:
my_data = [1,2,3,4,5]
my_data

[1, 2, 3, 4, 5]

In [58]:
gf = pd.DataFrame(my_data)
gf

0
0  1
1  2
2  3
3  4
4  5

In [59]:
tf = pd.DataFrame(my_data,index=(['a','b','c','d','e']))
tf

0
a  1
b  2
c  3
d  4
e  5

In [60]:
df.shape

(4, 4)

In [61]:
df.loc['a']

A    9
B    9
C    9
D    9
Name: a, dtype: int64

In [62]:
ft = pd.DataFrame(data=([[1,2,3,4],[3,4,6,7]]))
print(ft)

   0  1  2  3
0  1  2  3  4
1  3  4  6  7


In [63]:
ft = pd.DataFrame(data=([[1,2,3,4],[3,4,6,7]]),index=(['h','j']),columns=(['k','l','t','p']))

In [64]:
ft

k  l  t  p
h  1  2  3  4
j  3  4  6  7

In [65]:
i = [500,45,67,90,87]
i

[500, 45, 67, 90, 87]

In [66]:
e = ["even" if value%2==0 else "odd" for value in i]
e

['even', 'odd', 'odd', 'even', 'odd']

In [67]:
np.arange(.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [68]:
data = ("gg","hh","jj","kk")
data

('gg', 'hh', 'jj', 'kk')

In [69]:
name = "hello,how are you"
name

'hello,how are you'

In [70]:
name.upper()

'HELLO,HOW ARE YOU'

In [72]:
name.title()

'Hello,How Are You'

In [73]:
name.lower()

'hello,how are you'

In [74]:
name[:2]

'he'

In [75]:
name[-1:2]

''

In [76]:
name[-1]

'u'

In [78]:
tup1 = ('a','b','c','d')
if 'a' in tup1:
  print("value is present")
else:
  print("value is not present" )  

value is present


In [79]:
np.logspace(2,4,8)

array([  100.        ,   193.06977289,   372.75937203,   719.685673  ,
        1389.49549437,  2682.69579528,  5179.47467923, 10000.        ])

In [80]:
d = np.array([[1,0,0,1],[1,1,0,0],[0,0,1,1],[1,0,1,0]])
d

array([[1, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 0, 1, 1],
       [1, 0, 1, 0]])

In [81]:
d.ndim

2

In [82]:
d.shape

(4, 4)

In [83]:
d.size

16

In [86]:
s = np.diag([1,2,3,4])

In [87]:
s

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [88]:
a = np.array([10,0,2,-1])
b = np.array([0,0,40,6])

In [89]:
np.logical_or(a,b)

array([ True, False,  True,  True])

In [90]:
np.logical_xor(a,b)

array([ True, False, False, False])

In [92]:
a.mean()

2.75

In [93]:
np.median(b)

3.0

In [94]:
a.std()

4.322904116447646

In [95]:
df = df.T

In [96]:
df

a  b  c  d
A  9  9  9  9
B  9  9  9  9
C  9  9  9  9
D  9  9  9  9

In [97]:
df = pd.concat([df,tf])

In [98]:
df

a    b    c    d    0
A  9.0  9.0  9.0  9.0  NaN
B  9.0  9.0  9.0  9.0  NaN
C  9.0  9.0  9.0  9.0  NaN
D  9.0  9.0  9.0  9.0  NaN
a  NaN  NaN  NaN  NaN  1.0
b  NaN  NaN  NaN  NaN  2.0
c  NaN  NaN  NaN  NaN  3.0
d  NaN  NaN  NaN  NaN  4.0
e  NaN  NaN  NaN  NaN  5.0

In [99]:
df.columns

Index(['a', 'b', 'c', 'd', 0], dtype='object')

In [100]:
df.tail

<bound method NDFrame.tail of      a    b    c    d    0
A  9.0  9.0  9.0  9.0  NaN
B  9.0  9.0  9.0  9.0  NaN
C  9.0  9.0  9.0  9.0  NaN
D  9.0  9.0  9.0  9.0  NaN
a  NaN  NaN  NaN  NaN  1.0
b  NaN  NaN  NaN  NaN  2.0
c  NaN  NaN  NaN  NaN  3.0
d  NaN  NaN  NaN  NaN  4.0
e  NaN  NaN  NaN  NaN  5.0>

In [101]:
df.head()

a    b    c    d    0
A  9.0  9.0  9.0  9.0  NaN
B  9.0  9.0  9.0  9.0  NaN
C  9.0  9.0  9.0  9.0  NaN
D  9.0  9.0  9.0  9.0  NaN
a  NaN  NaN  NaN  NaN  1.0

In [102]:
b = np.array([1,2,3,4,5])

In [ ]:
b

In [103]:
b.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [104]:
d = {'x':40,'y':50,'z':60}
d

{'x': 40, 'y': 50, 'z': 60}

In [109]:
x="pappu"
x

'pappu'

In [110]:
x.isalnum()

True

In [111]:
x.isdigit()

False

In [112]:
x.encode()

b'pappu'

In [113]:
x.casefold()

'pappu'

In [114]:
x.capitalize()

'Pappu'

In [115]:
list=["mang0",1,7,"banana","cherry"]
list

['mang0', 1, 7, 'banana', 'cherry']

In [116]:
list[1]="nimbu"
list

['mang0', 'nimbu', 7, 'banana', 'cherry']

In [117]:
mylist=list.copy()
mylist

['mang0', 'nimbu', 7, 'banana', 'cherry']

In [118]:
list3=list+mylist
list3

['mang0',
 'nimbu',
 7,
 'banana',
 'cherry',
 'mang0',
 'nimbu',
 7,
 'banana',
 'cherry']

In [119]:
list.extend(mylist)
list

['mang0',
 'nimbu',
 7,
 'banana',
 'cherry',
 'mang0',
 'nimbu',
 7,
 'banana',
 'cherry']

In [120]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [121]:
np.random.rand(4,4)

array([[0.68448352, 0.892576  , 0.60075966, 0.12495123],
       [0.10777711, 0.06865412, 0.53216241, 0.57042572],
       [0.2267545 , 0.8775954 , 0.7610227 , 0.13034483],
       [0.15099619, 0.05808404, 0.06322017, 0.62561529]])

In [123]:
np.random.randn(2,3)

array([[-1.33922912,  0.48782202, -0.1667052 ],
       [-0.62371868,  0.92518454,  0.2689509 ]])